"""The SCENE bank's identity. mel16.h has had a regeneration test since it shipped; mel_scene.h
has had nothing, and it is the bank every one of the 41,507 corpus scene rows was filtered with.

⚠️WHY A TEST RATHER THAN A COMMENT. The scene bank's axis was pinned by nothing: gen_mel_scene.py
took `layout` and `f_hi` from hear.sketch's module-level defaults by omission, so flipping
SK.mel_filterbank's default layout would silently re-band every future scene row while the header
still said `// GENERATED by`. Both are written LITERALLY here, not imported from SK, so a change
on either side breaks this test instead of the corpus.

⚠️THE TWO LITERALS ARE NOT EQUALLY LOAD-BEARING, measured rather than assumed. Under NYQUIST the
bank's top edge is clamped to fs/2*0.98 = 7840 Hz, so at 16 kHz ANY f_hi >= 7840 emits the same
233 weights -- swapping 20000 for 8000 changes nothing. The LAYOUT literal is the one that bites:
`fixed` re-bands every band. So `WANT_F_HI` guards only an f_hi edit below the clamp, and it is
`WANT_LAYOUT` plus the byte-exact regeneration test that pin this bank.

⚠️A GUARD ON THE EDGES IS NOT A GUARD ON THE BANK. hear/pool.py refuses to stack rows whose
(bands, slices, f_lo_hz, f_hi_hz) differ, which catches a moved rate, nfft or band count -- but
two banks can share all four edges and differ in the WEIGHTS between them. That residual is what
the byte-exact regeneration test below covers. Neither is complete alone.

There is no ESP32 toolchain in CI, so this reads the generated header, exactly as
tests/test_firmware_mel16.py does.
"""
import pathlib
import re
import subprocess
import sys

import numpy as np
import pytest

from hear import sketch as SK

ROOT = pathlib.Path(__file__).resolve().parents[1]
SCENE_H = ROOT / "firmware" / "night_node" / "mel_scene.h"
MEL16_H = ROOT / "firmware" / "night_node" / "mel16.h"
GEN = ROOT / "firmware" / "gen_mel_scene.py"

# ⚠️LITERAL ON PURPOSE. Importing these from SK would make the test agree with whatever SK says
# today, which is the exact failure it exists to catch.
WANT_FS = 16000.0
WANT_NFFT = 256
WANT_BANDS = 20
WANT_F_HI = 20000.0
WANT_LAYOUT = "nyquist"


def _load(path):
    if not path.exists():
        pytest.skip("%s not in this checkout" % path)
    h = path.read_text()

    def d(n):
        m = re.search(r"#define\s+%s\s+(0x[0-9a-fA-F]+|[0-9.]+f?)" % n, h)
        assert m, "%s missing from %s" % (n, path.name)
        v = m.group(1)
        return int(v, 16) if v.startswith("0x") else float(v.rstrip("f"))

    def arr(n):
        m = re.search(r"\b%s\[\d+\]\s*=\s*\{(.*?)\};" % n, h, re.S)
        assert m, "%s missing from %s" % (n, path.name)
        return [float(t) for t in re.findall(r"-?[0-9.]+(?:e[-+]?\d+)?", m.group(1).replace("f", ""))]

    return d, arr


def _pairs(path, pre):
    """[(first bin, bin count)] per band, as the header states them."""
    _d, arr = _load(path)
    lo = [int(v) for v in arr("%s_FB_LO" % pre)]
    n = [int(v) for v in arr("%s_FB_N" % pre)]
    return list(zip(lo, n))


def test_the_compiled_scene_bank_is_the_bank_its_generator_names():
    """mel_scene.h IS mel_filterbank(16000, 256, 20, f_lo=fs/nfft, f_hi=20000, layout='nyquist').

    The layout and f_hi are spelled out here rather than imported, so this fails if either the
    generator or hear.sketch moves. Together with the regeneration test below it is what stands
    between an edit to SK's defaults and a silently re-banded scene corpus.
    """
    d, arr = _load(SCENE_H)
    fs, nfft, bands = d("MELS_FS"), int(d("MELS_NFFT")), int(d("MELS_BANDS"))
    assert (fs, nfft, bands) == (WANT_FS, WANT_NFFT, WANT_BANDS)
    lo = [int(v) for v in arr("MELS_FB_LO")]
    n = [int(v) for v in arr("MELS_FB_N")]
    w = np.array(arr("MELS_FB_W"))

    fb = SK.mel_filterbank(fs, nfft, bands, f_lo=fs / nfft, f_hi=WANT_F_HI, layout=WANT_LAYOUT)
    off = 0
    for b in range(bands):
        idx = np.nonzero(fb[b])[0]
        assert len(idx), "band %d empty in hear, populated on the node" % b
        assert (int(idx[0]), len(idx)) == (lo[b], n[b]), \
            "band %d spans bins %d..%d in hear, %d..%d on the node" % (
                b, idx[0], idx[-1], lo[b], lo[b] + n[b] - 1)
        got, want = w[off:off + n[b]], fb[b][lo[b]:lo[b] + n[b]]
        off += n[b]
        assert np.abs(got - want).max() < 1e-6, "band %d weights differ" % b
    assert off == len(w), "%d weights in the header, %d consumed by the bands" % (len(w), off)


def test_the_declared_edges_describe_the_table():
    """MELS_F_LO/MELS_F_HI are what the node writes into every scene row's f_lo_hz/f_hi_hz, and
    hear/pool.py now refuses to stack rows that disagree on them. If the defines drift from the
    table they claim to describe, that guard is comparing labels rather than band axes."""
    d, arr = _load(SCENE_H)
    fs, nfft, bands = d("MELS_FS"), int(d("MELS_NFFT")), int(d("MELS_BANDS"))
    lo = [int(v) for v in arr("MELS_FB_LO")]
    n = [int(v) for v in arr("MELS_FB_N")]
    freqs = np.fft.rfftfreq(nfft, 1.0 / fs)
    assert d("MELS_F_LO") == pytest.approx(freqs[lo[0]]) == pytest.approx(62.5)
    top = lo[bands - 1] + n[bands - 1] - 1
    assert d("MELS_F_HI") == pytest.approx(freqs[top]) == pytest.approx(7812.5)


def test_no_band_is_empty_and_none_of_them_sits_on_DC():
    """The generator's own two refusals, asserted against the shipped artefact.

    An empty band emits a constant -120 dB column that reads as a measurement of silence. A band
    holding bin 0 emits the DC offset the node's 1.6 Hz block exists to remove, as if it were
    signal -- which is why the generator sets F_LO = FS/NFFT, bin 1, rather than lower.

    ⚠️THE DC HALF USED TO BE DEAD. It read `assert lo > 0 or b == 0`, and band 0 is the ONLY band
    that can hold bin 0, so the clause exempted the single case it was written for and could not
    fail. Scoped honestly: measured against today's generator it still cannot fail from a constant
    edit, because mel_filterbank's triangle rises from zero AT its lower edge, so bin 0 gets weight
    exactly 0.0 even at f_lo=0.0 -- checked at f_lo in (0, 10, 20, 31.25, 62.5), all of which put
    band 0 at bin 1. What it does cover is the ARTEFACT: a hand-edited mel_scene.h, or a future
    bank whose windows are not triangles-from-zero. `MELS_FB_LO[0] == 1` below is the falsifiable
    half -- raising F_LO moves it (f_lo=300 would give bin 5).
    """
    pairs = _pairs(SCENE_H, "MELS")
    for b, (lo, n) in enumerate(pairs):
        assert n > 0, "scene band %d has no FFT bins under it" % b
        assert lo > 0, "band %d holds bin 0 (DC)" % b
    assert pairs[0][0] == 1, \
        "band 0 starts at bin %d, not the first bin above DC -- F_LO has moved" % pairs[0][0]


def test_the_generators_fixed_layout_count_is_this_banks_number_not_the_sketchs():
    """⚠️A CONSTANT TRANSPLANTED BETWEEN TWO BANKS. gen_mel_scene.py justifies LAYOUT=nyquist by
    what FIXED would cost, and said `5 of 20 bands above Nyquist and empty`. Measured with THIS
    bank's own f_lo (62.5 Hz = FS/NFFT) the answer is 4, bands 16..19. The 5 is mel_filterbank's
    docstring number, and that one is for SK.F_LO=300 -- a different lower edge gives different
    mel edges all the way up. Both counts are asserted here so the comment cannot drift back.
    """
    def empties(f_lo, layout):
        fb = SK.mel_filterbank(WANT_FS, WANT_NFFT, WANT_BANDS, f_lo=f_lo, f_hi=WANT_F_HI,
                               layout=layout)
        return [b for b in range(WANT_BANDS) if not len(np.nonzero(fb[b])[0])]

    assert empties(WANT_FS / WANT_NFFT, "fixed") == [16, 17, 18, 19]      # this bank: 4
    assert len(empties(300.0, "fixed")) == 5                              # the sketch's: 5
    assert empties(WANT_FS / WANT_NFFT, WANT_LAYOUT) == []                # shipped: none


def test_regenerating_the_header_reproduces_it_byte_for_byte(tmp_path):
    """Proves the explicit `layout=` and literal `f_hi` in gen_mel_scene.py are a true no-op
    against the committed bank -- and that the committed bank is still what the generator emits."""
    out = tmp_path / "mel_scene.h"
    r = subprocess.run([sys.executable, str(GEN), str(out)], capture_output=True, text=True)
    assert r.returncode == 0, r.stderr
    assert out.read_bytes() == SCENE_H.read_bytes(), \
        "firmware/night_node/mel_scene.h is not what gen_mel_scene.py emits -- regenerate it"


def test_the_scene_bank_is_not_the_detection_bank():
    """Band k on a scene row and band k on a sketch frame are different frequencies. They overlap
    (scene band 2 is bins 5-8, detection band 0 is bins 5-10, sharing four bins) but no band of
    one IS a band of the other, so nothing may stack a scene row with a sketch frame."""
    scene = _pairs(SCENE_H, "MELS")
    det = _pairs(MEL16_H, "MEL16")
    shared = set(scene) & set(p for p in det if p != (0, 0))
    assert not shared, "these (first bin, bin count) pairs occur in BOTH banks: %s" % sorted(shared)
    assert scene[2][0] == det[0][0], "the overlap this test is bounding has moved; re-read both banks"
