#!/usr/bin/env python3
"""Generate firmware/night_node/decim.h -- the anti-alias FIR the /2 decimator runs.

    python3 firmware/gen_decim.py > firmware/night_node/decim.h

⚠️THE FILTER REPLACES ONE THE MICROPHONE USED TO PROVIDE. Running the PDM mic at 16 kHz let its
internal decimator do the anti-aliasing. Acquiring at 32 kHz and decimating in software moves that
job here, so this filter must not be worse than the one it displaces or the scene corpus quietly
degrades at the top of its band -- and the corpus has 228k rows measured through the old path.

The requirement is set by the mel banks, not by taste: MELS_F_HI is 7812.5 Hz, so everything above
2*8000 - 7812.5 = 8187.5 Hz folds into a band that is actually used. Passband to 7812.5, stopband
from 8187.5 -- a 375 Hz transition, which is what makes this 257 taps rather than a cheap halfband.
A 33-tap halfband was measured at only -7.7 dB worst-case fold and was rejected.

48 kHz is the CEILING, not a preference. The mic's Standard Performance Mode tops out at a 4.0 MHz
clock (datasheet V1.2, Dec 2018) and the ESP32 drives PDM at fs * 64 in I2S_PDM_DSR_8S, so
fs <= 62.5 kHz. Of the rates under that, only 32 kHz (/2) and 48 kHz (/3) decimate to the mel
banks' 16 kHz by an INTEGER; 64 kHz would be a clean /4 and needs 4.096 MHz, which the mic does
not support. So /3 from 48 kHz is the most band this part can legally be clocked for.

⚠️/3 HAS MORE ALIAS IMAGES THAN /2. Decimating by 3 folds both the k=1 and k=2 images of 16 kHz
into the used band, so the stopband runs from 8187.5 Hz all the way to Nyquist, and every image is
measured below -- not just the first one.

MEASURED ON THE QUANTISED TAPS, which is the only measurement that means anything -- the float
design reads better and the int16 filter that actually runs does not:
  passband ripple      <= 0.08 dB over 62.5-7812.5 Hz
  worst fold into band    -63.4 dB
  group delay          224 acquisition samples = 4.67 ms
  CPU                  449 taps x 256 outputs x 62.5 blocks/s = 7.2 M MAC/s, ~3% of one core
"""
import sys

import numpy as np
from scipy import signal

FS_ACQ, DECIM = 48000.0, 3
TOP, STOP, TAPS = 7812.5, 8187.5, 449


def design():
    h = signal.remez(TAPS, [0, TOP, STOP, FS_ACQ / 2], [1, 0], weight=[1, 60], fs=FS_ACQ)
    # ⚠️NORMALISE BEFORE QUANTISING, NOT AFTER. remez returns a passband gain near but not equal to
    # 1 -- measured 1.0106 here -- and forcing unity by pushing the whole residual onto the centre
    # tap adds a 347 LSB delta, which is a BROADBAND impulse: it flattened the stopband to -39.5 dB
    # from the -74.8 dB the design achieves. The stopband floor was set by the correction, not by
    # Q15. Scale first, and the leftover is then a couple of LSB that the centre tap can absorb.
    h = h / h.sum()
    q = np.round(h * 32768.0).astype(np.int64)
    resid = 32768 - int(q.sum())
    assert abs(resid) <= 8, "residual %d LSB is too large to absorb; the design is not normalised" % resid
    q[TAPS // 2] += resid
    assert q.sum() == 32768, q.sum()
    assert np.abs(q).max() < 32768, "a tap does not fit int16"
    return h, q


def main():
    h, q = design()
    w, H = signal.freqz(q / 32768.0, worN=32768, fs=FS_ACQ)
    a = np.abs(H)
    at = lambda f: 20 * np.log10(np.interp(f, w, a) + 1e-12)          # noqa: E731
    grid = np.linspace(62.5, TOP, 400)
    ripple = max(abs(at(f)) for f in grid)
    fsd = FS_ACQ / DECIM
    fold = max(max(at(k * fsd - f), at(k * fsd + f))
               for f in grid for k in range(1, DECIM) if k * fsd + f <= FS_ACQ / 2)
    out = [
        "// GENERATED by firmware/gen_decim.py -- do not edit.",
        "// Anti-alias FIR for the %d -> %d Hz decimator." % (FS_ACQ, FS_ACQ / DECIM),
        "// Measured on the QUANTISED taps, not the float design:",
        "//   passband ripple <= %.2f dB over %.1f-%.1f Hz" % (ripple, 62.5, TOP),
        "//   worst fold into that band %+.1f dB" % fold,
        "//   DC gain exactly 1.0 (taps sum to 32768)",
        "#pragma once",
        "#define DECIM_TAPS   %d" % TAPS,
        "#define DECIM_DELAY  %d   // acquisition samples, (TAPS-1)/2. NOT required to be a" % ((TAPS - 1) // 2),
        "                          // multiple of DECIM: acq_of() subtracts it in the ACQUISITION",
        "                          // domain, where it is a whole number by construction.",
        "#define DECIM_SHIFT  15",
        "static const int16_t DECIM_H[DECIM_TAPS] = {",
    ]
    for i in range(0, TAPS, 12):
        out.append("  " + ", ".join("%6d" % v for v in q[i:i + 12]) + ",")
    out.append("};")
    sys.stdout.write("\n".join(out) + "\n")
    print("  ripple %.3f dB, fold %+.1f dB, delay %d" % (ripple, fold, (TAPS - 1) // 2), file=sys.stderr)


if __name__ == "__main__":
    main()
