#!/usr/bin/env python3
"""Emit firmware/night_node/mel_scene.h -- a SECOND mel filterbank, for the scene descriptor only.

WHY A SECOND BANK RATHER THAN A WIDER FIRST ONE. The detection sketch's bank (MEL16_*, from
gen_mel.py) is frozen: firmware/hear_poc checks it byte-exact against golden vectors, hear/wire.py
profile 0 IS the 20x8 shape at f_lo=300 and cannot be reinterpreted without invalidating every
frame already on the wire. The scene descriptor has no wire profile, no trained model and -- as of
this writing -- no captured rows at all, so its banding is the one that is free to move.

WHY IT MOVES DOWN. Measured off this node's live ring, a 10 s pull, energy relative to the whole:
    2-62 Hz -6.2 dB | 62-312 Hz -1.9 dB | 312-500 Hz -11.9 dB | 500-1k -16.2 dB
    1-2k -22.3 dB | 2-4k -27.8 dB | 4-8k -26.3 dB
62-312 Hz carries +8.2 dB more than everything above 312 Hz combined, and MEL16_FB_LO[0] = 5 puts
the detection bank's first bin at 312.5 Hz -- so all of it is captured, survives the 1.6 Hz DC
block, reaches the PSRAM ring, and is then discarded. This bank starts at FFT bin 1 instead.

Everything here is derived from hear.sketch, read-only. This script does not import for its
constants MEL_BANDS/F_LO/NFFT being editable -- it passes its own f_lo explicitly and leaves
SK.F_LO alone, which is what keeps gen_mel.py's and gen_golden.py's output byte-identical.

    python3 firmware/gen_mel_scene.py
"""
import os
import sys

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from hear import sketch as SK

FS = 16000.0
# Band count stays at SK.MEL_BANDS. Not because the wire needs it -- the scene row is a bare hex
# array in a CSV with its own `bands` column, and nothing caps it -- but because the card does:
# 20 bands x 4 slices is the ~227 B row the 9.6 MB-per-12 h arithmetic in night_node.ino is built
# on, and moving it would move that too. Changing the SPAN is free; changing the COUNT is not.
BANDS = SK.MEL_BANDS
# Bin 1 of a 256-point FFT at 16 kHz = 62.5 Hz. Bin 0 is DC and the node's 1.6 Hz DC block has
# already removed what would be there.
F_LO = FS / SK.NFFT
# SK.mel_filterbank clamps its own upper edge to fs/2*0.98 = 7840 Hz, so the top band ends at bin
# 125 = 7812.5 Hz whatever is asked for here. That clamp is hear/sketch.py's and is not touched.
F_HI = SK.F_HI


def carr(name, vals, per=6, ctype="float"):
    toks = [v if isinstance(v, str) else (("%.9ef" % v) if ctype == "float" else ("%d" % v)) for v in vals]
    lines, cur = [], ""
    for i, t in enumerate(toks):
        cur += t + ","
        if (i + 1) % per == 0:
            lines.append("  " + cur); cur = ""
    if cur:
        lines.append("  " + cur)
    return "static const %s %s[%d] = {\n%s\n};\n" % (ctype, name, len(vals), "\n".join(lines))


fb = SK.mel_filterbank(FS, SK.NFFT, BANDS, F_LO, F_HI)
freqs = np.fft.rfftfreq(SK.NFFT, 1.0 / FS)
lo_n, flat, empty = [], [], 0
for b in range(BANDS):
    idx = np.nonzero(fb[b])[0]
    if len(idx) == 0:
        lo_n.append((0, 0)); empty += 1; continue
    lo, hi = int(idx[0]), int(idx[-1]) + 1
    lo_n.append((lo, hi - lo))
    flat.extend(fb[b][lo:hi].tolist())
# A band with no bins under it would emit a constant -120 dB column that looks like real data.
# Refuse rather than ship one.
if empty:
    raise SystemExit("%d empty band(s) at f_lo=%.1f, nfft=%d, bands=%d" % (empty, F_LO, SK.NFFT, BANDS))

edge = "// band  bins            Hz\n" + "\n".join(
    "//  %2d   %3d-%3d   %8.1f-%8.1f" % (b, lo_n[b][0], lo_n[b][0] + lo_n[b][1] - 1,
                                         freqs[lo_n[b][0]], freqs[lo_n[b][0] + lo_n[b][1] - 1])
    for b in range(BANDS))

out = ["// GENERATED by firmware/gen_mel_scene.py -- do not edit.",
       "// The SCENE descriptor's filterbank. Separate from mel16.h on purpose: MEL16_* is the",
       "// detection sketch's bank and is frozen byte-exact against firmware/hear_poc's golden",
       "// vectors and against hear/wire.py profile 0. This one spans lower.",
       "//",
       "// No window is emitted. np.hanning(nfft) is a function of nfft alone, so MEL16_WIN is the",
       "// same array this bank would produce; night_node.ino static_asserts the two NFFTs match",
       "// and reuses it, saving 1024 B of flash for a duplicate.",
       "//",
       edge,
       "#pragma once", "#include <stdint.h>",
       "", "#define MELS_FS     %.1ff" % FS,
       "#define MELS_NFFT   %d" % SK.NFFT,
       "#define MELS_BANDS  %d" % BANDS,
       "#define MELS_F_LO   %.1ff" % freqs[lo_n[0][0]],
       "#define MELS_F_HI   %.1ff" % freqs[lo_n[BANDS - 1][0] + lo_n[BANDS - 1][1] - 1],
       "",
       carr("MELS_FB_LO", [v[0] for v in lo_n], per=20, ctype="uint16_t"),
       carr("MELS_FB_N", [v[1] for v in lo_n], per=20, ctype="uint16_t"),
       carr("MELS_FB_W", flat)]
p = os.path.join(os.path.dirname(os.path.abspath(__file__)), "night_node", "mel_scene.h")
os.makedirs(os.path.dirname(p), exist_ok=True)
open(p, "w").write("\n".join(out))
print("wrote %s : %d bands, %.1f-%.1f Hz, %d weights, %d B of tables"
      % (p, BANDS, freqs[lo_n[0][0]], freqs[lo_n[BANDS - 1][0] + lo_n[BANDS - 1][1] - 1],
         len(flat), 4 * len(flat) + 4 * BANDS))
