#!/usr/bin/env python3
"""Emit the two node-side mel filterbanks, one per node class, at that node's own rate.

`MEL16_*` -> firmware/path_test/mel16.h, 16 kHz -- path_test.ino:143 feeds MEL16_FS straight into
i2s.begin as the PDM mic's OWN capture rate, so this bank must never move to follow the other one.

`MELIMP_*` -> firmware/night_node/mel_impulse.h, 48 kHz -- night_node's FS_ACQ, the rate the
sketch ring is fed at. Two names because a shared prefix would let regenerating one silently
change the other's baked-in rate the moment they disagreed; see night_node.ino's static_asserts.

The filterbank depends on fs; the Hann window does not. golden.h carries the 48 kHz bank for the
byte-exactness check, this carries the two live-capture banks.

⚠️THE FIXED BAND LAYOUT, AND WHY A NODE CANNOT JUST SET THE FLAG. Under the legacy layout the
bank is rescaled to each node's Nyquist, so band 12 is 5826 Hz on a 48 kHz phone and 3072 Hz at
16 kHz. Setting the layout bit without regenerating this table would ship a frame that CLAIMS the
shared axis and carries rescaled data -- worse than not setting it, because the far side would
then stack it with a phone's. The bit and the table are emitted together, from one call to
hear.sketch, so they cannot disagree.

At 16 kHz the fixed axis leaves 15 of 20 bands below Nyquist; at 48 kHz all 20 are real. The
`_VALID_BANDS` macro says how many are real so a consumer masks the rest rather than reading them
as measurements of silence. The frame stays 20 bands and 172 B at both rates on purpose -- that is
what lets the two rates stack in one pool and one model.
"""
import os
import sys

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from hear import sketch as SK

LAYOUT = SK.LAYOUT_FIXED

# (fs, prefix, path relative to firmware/) -- one row per node class. Adding a third node at a
# third rate is one more row here, not a second script.
TARGETS = [
    (16000.0, "MEL16", os.path.join("path_test", "mel16.h")),
    (48000.0, "MELIMP", os.path.join("night_node", "mel_impulse.h")),
]


def carr(name, vals, per=6, ctype="float"):
    toks = [v if isinstance(v, str) else (("%.9ef" % v) if ctype == "float" else ("%d" % v)) for v in vals]
    lines, cur = [], ""
    for i, t in enumerate(toks):
        cur += t + ","
        if (i + 1) % per == 0:
            lines.append("  " + cur); cur = ""
    if cur:
        lines.append("  " + cur)
    return "static const %s %s[%d] = {\n%s\n};\n" % (ctype, name, len(vals), "\n".join(lines))


def emit(fs, prefix):
    """(header text, hop, weight count) for one bank at `fs`, symbols named `{prefix}_*`."""
    fb = SK.mel_filterbank(fs, layout=LAYOUT)
    lo_n, flat = [], []
    for b in range(SK.MEL_BANDS):
        idx = np.nonzero(fb[b])[0]
        if len(idx) == 0:
            lo_n.append((0, 0)); continue
        lo, hi = int(idx[0]), int(idx[-1]) + 1
        lo_n.append((lo, hi - lo))
        flat.extend(fb[b][lo:hi].tolist())

    win = np.hanning(SK.NFFT)
    hop = max(1, int(SK.HOP_S * fs))
    out = ["// GENERATED by firmware/gen_mel.py -- do not edit.",
           "// Self-contained: window, filterbank and the sizes that define the wire format, so a node",
           "// sketch does not have to drag in golden.h and its 48000-sample test vector.",
           "#pragma once", "#include <stdint.h>",
           "", "#define %s_FS     %.1ff" % (prefix, fs),
           "#define %s_HOP    %d" % (prefix, hop),
           "#define %s_NFFT   %d" % (prefix, SK.NFFT),
           "#define %s_BANDS  %d" % (prefix, SK.MEL_BANDS),
           "#define %s_FRAMES %d" % (prefix, SK.FRAMES),
           "#define %s_FRAME_BYTES %d" % (prefix, SK.wire_size()),
           "",
           "// The frame states its own rate and band layout: flags bits 8-11 carry the rate code and",
           "// bit 12 says these edges are on the shared [F_LO, F_HI] axis rather than rescaled to this",
           "// node's Nyquist. Without them a consumer cannot tell a 16 kHz frame from a 48 kHz one and",
           "// band k is a different frequency in each.",
           "#define %s_FS_CODE    %d" % (prefix, SK.fs_code(fs)),
           "#define %s_LAYOUT_BIT 0x%04x" % (prefix, SK.LAYOUT_BIT if LAYOUT == SK.LAYOUT_FIXED else 0),
           "#define %s_FLAG_BITS  ((%s_FS_CODE << %d) | %s_LAYOUT_BIT)" % (prefix, prefix, SK.FS_SHIFT, prefix),
           "// Bands with any bin below Nyquist. The rest are empty BY CONSTRUCTION, not quiet.",
           "#define %s_VALID_BANDS %d" % (prefix, SK.valid_bands(fs, layout=LAYOUT)), "",
           carr("%s_WIN" % prefix, ["%.9ef" % v for v in win], per=6),
           carr("%s_FB_LO" % prefix, [v[0] for v in lo_n], per=20, ctype="uint16_t"),
           carr("%s_FB_N" % prefix, [v[1] for v in lo_n], per=20, ctype="uint16_t"),
           carr("%s_FB_W" % prefix, flat)]
    return "\n".join(out), hop, len(flat)


if __name__ == "__main__":
    here = os.path.dirname(os.path.abspath(__file__))
    for fs, prefix, rel in TARGETS:
        text, hop, n_w = emit(fs, prefix)
        p = os.path.join(here, rel)
        os.makedirs(os.path.dirname(p), exist_ok=True)
        open(p, "w").write(text)
        print("%d -> %s  (%s_*, hop %d, %d weights, valid_bands %d/%d) wrote %s"
              % (int(fs), os.path.dirname(rel), prefix, hop, n_w,
                 SK.valid_bands(fs, layout=LAYOUT), SK.MEL_BANDS, p))
