#!/usr/bin/env python3
"""Emit firmware/hear_poc/golden.h from the Python reference.

The firmware is checked against THIS, not against opinion. Regenerate whenever hear/ changes:

    python3 firmware/gen_golden.py

Signal is tests/test_node.py::_shot verbatim, so the vectors trace to the suite that already
pins the platform's behaviour.
"""
import os
import sys

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from hear import sketch as SK
from hear.node import detect as DT
from hear.node.pipeline import Pipeline

FS = 48000.0


def shot(n=48000, at=8000, amp=25000.0):
    x = np.random.RandomState(1).normal(0, 40, n)
    x[at:at + 20] += amp * np.hanning(20)
    x[at + 20:at + 900] += amp * 0.25 * np.exp(-np.arange(880) / 200.0) * \
        np.random.RandomState(2).normal(0, 1, 880)
    return x


def carr(name, vals, fmt="%d", per=16, ctype="int16_t"):
    body = ",".join(fmt % v for v in vals)
    wrapped, line = [], ""
    for i, tok in enumerate(body.split(",")):
        line += tok + ","
        if (i + 1) % per == 0:
            wrapped.append("  " + line)
            line = ""
    if line:
        wrapped.append("  " + line)
    return "static const %s %s[%d] = {\n%s\n};\n" % (ctype, name, len(vals), "\n".join(wrapped))


def main():
    x = shot()
    xi = np.clip(np.round(x), -32768, 32767).astype(np.int16)

    dets = Pipeline(FS).run(xi.astype(float))
    assert dets, "reference pipeline found nothing"
    d = dets[0]
    q, ref = SK.sketch(xi.astype(float)[d["index"]:], FS)
    frame = SK.pack(d["index"] % 1_000_000, ref, int(min(d["peak"], 65535)), q, flags=0)

    fb = SK.mel_filterbank(FS)
    win = np.hanning(SK.NFFT)

    out = ['// GENERATED by firmware/gen_golden.py -- do not edit.',
           '// Reference: hear/sketch.py, hear/node/detect.py at the commit that produced it.',
           '#pragma once', '#include <stdint.h>', '',
           '#define GOLD_FS        %.1ff' % FS,
           '#define GOLD_N         %d' % len(xi),
           '#define GOLD_BANDS     %d' % SK.MEL_BANDS,
           '#define GOLD_FRAMES    %d' % SK.FRAMES,
           '#define GOLD_NFFT      %d' % SK.NFFT,
           '#define GOLD_HOP       %d' % max(1, int(SK.HOP_S * FS)),
           '#define GOLD_DET_INDEX %d' % d["index"],
           '#define GOLD_DET_PEAK  %d' % int(min(d["peak"], 65535)),
           '#define GOLD_REF_DB    %.9ff' % ref,
           '#define GOLD_FRAME_LEN %d' % len(frame), '',
           carr("GOLD_X", xi.tolist()),
           carr("GOLD_FRAME", list(frame), per=20, ctype="uint8_t"),
           carr("GOLD_WIN", ["%.9ef" % v for v in win], fmt="%s", per=6, ctype="float"),
           ]
    # mel filterbank as (band, first_bin, n_bins, weights...) -- sparse, since most bins are 0
    nz = []
    flat = []
    for b in range(SK.MEL_BANDS):
        idx = np.nonzero(fb[b])[0]
        if len(idx) == 0:
            nz.append((0, 0)); continue
        lo, hi = int(idx[0]), int(idx[-1]) + 1
        nz.append((lo, hi - lo))
        flat.extend(fb[b][lo:hi].tolist())
    out.append(carr("GOLD_FB_LO", [v[0] for v in nz], per=20, ctype="uint16_t"))
    out.append(carr("GOLD_FB_N", [v[1] for v in nz], per=20, ctype="uint16_t"))
    out.append(carr("GOLD_FB_W", ["%.9ef" % v for v in flat], fmt="%s", per=6, ctype="float"))

    p = os.path.join(os.path.dirname(os.path.abspath(__file__)), "hear_poc", "golden.h")
    open(p, "w").write("\n".join(out))
    print("wrote %s" % p)
    print("  detection index %d peak %d ref_db %.4f frame %d B" %
          (d["index"], int(d["peak"]), ref, len(frame)))
    print("  filterbank: %d non-zero weights across %d bands" % (len(flat), SK.MEL_BANDS))


if __name__ == "__main__":
    main()
