#!/usr/bin/env python3
"""Emit firmware/path_test/mel16.h -- the mel filterbank at the PDM mic's rate.

The filterbank depends on fs; the Hann window does not. golden.h carries the 48 kHz bank for the
byte-exactness check, this carries 16 kHz for live capture off the Sense's onboard PDM mic.
"""
import os
import sys

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from hear import sketch as SK

FS = 16000.0


def carr(name, vals, per=6, ctype="float"):
    toks = [v if isinstance(v, str) else (("%.9ef" % v) if ctype == "float" else ("%d" % v)) for v in vals]
    lines, cur = [], ""
    for i, t in enumerate(toks):
        cur += t + ","
        if (i + 1) % per == 0:
            lines.append("  " + cur); cur = ""
    if cur:
        lines.append("  " + cur)
    return "static const %s %s[%d] = {\n%s\n};\n" % (ctype, name, len(vals), "\n".join(lines))


fb = SK.mel_filterbank(FS)
lo_n, flat = [], []
for b in range(SK.MEL_BANDS):
    idx = np.nonzero(fb[b])[0]
    if len(idx) == 0:
        lo_n.append((0, 0)); continue
    lo, hi = int(idx[0]), int(idx[-1]) + 1
    lo_n.append((lo, hi - lo))
    flat.extend(fb[b][lo:hi].tolist())

win = np.hanning(SK.NFFT)
out = ["// GENERATED by firmware/gen_mel.py -- do not edit.",
       "// Self-contained: window, filterbank and the sizes that define the wire format, so a node",
       "// sketch does not have to drag in golden.h and its 48000-sample test vector.",
       "#pragma once", "#include <stdint.h>",
       "", "#define MEL16_FS     %.1ff" % FS,
       "#define MEL16_HOP    %d" % max(1, int(SK.HOP_S * FS)),
       "#define MEL16_NFFT   %d" % SK.NFFT,
       "#define MEL16_BANDS  %d" % SK.MEL_BANDS,
       "#define MEL16_FRAMES %d" % SK.FRAMES,
       "#define MEL16_FRAME_BYTES %d" % SK.wire_size(), "",
       carr("MEL16_WIN", ["%.9ef" % v for v in win], per=6),
       carr("MEL16_FB_LO", [v[0] for v in lo_n], per=20, ctype="uint16_t"),
       carr("MEL16_FB_N", [v[1] for v in lo_n], per=20, ctype="uint16_t"),
       carr("MEL16_FB_W", flat)]
p = os.path.join(os.path.dirname(os.path.abspath(__file__)), "path_test", "mel16.h")
os.makedirs(os.path.dirname(p), exist_ok=True)
open(p, "w").write("\n".join(out))
print("wrote %s : hop %d, %d weights" % (p, max(1, int(SK.HOP_S * FS)), len(flat)))
