#!/usr/bin/env python3
"""Emit mel16.h -- the mel filterbank at the PDM mic's rate.

The filterbank depends on fs; the Hann window does not. golden.h carries the 48 kHz bank for the
byte-exactness check, this carries 16 kHz for live capture off the Sense's onboard PDM mic.

⚠️THE FIXED BAND LAYOUT, AND WHY A NODE CANNOT JUST SET THE FLAG. Under the legacy layout the
bank is rescaled to each node's Nyquist, so band 12 is 5826 Hz on a 48 kHz phone and 3072 Hz
here. Setting the layout bit without regenerating this table would ship a frame that CLAIMS the
shared axis and carries rescaled data -- worse than not setting it, because the far side would
then stack it with a phone's. The bit and the table are emitted together, from one call to
hear.sketch, so they cannot disagree.

At 16 kHz the fixed axis leaves 15 of 20 bands below Nyquist. The other five get no FFT bins,
sum to zero and quantise to the floor; `MEL16_VALID_BANDS` says how many are real so a consumer
masks them rather than reading them as measurements of silence. The frame stays 20 bands and
172 B on purpose -- a 15-band frame would be smaller but would not stack with a phone's 20.

⚠️WRITES BOTH COPIES. night_node/ and path_test/ each carry a mel16.h and only path_test's was
generated; they happened to be identical, which is not a guarantee.
"""
import os
import sys

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from hear import sketch as SK

FS = 16000.0
LAYOUT = SK.LAYOUT_FIXED


def carr(name, vals, per=6, ctype="float"):
    toks = [v if isinstance(v, str) else (("%.9ef" % v) if ctype == "float" else ("%d" % v)) for v in vals]
    lines, cur = [], ""
    for i, t in enumerate(toks):
        cur += t + ","
        if (i + 1) % per == 0:
            lines.append("  " + cur); cur = ""
    if cur:
        lines.append("  " + cur)
    return "static const %s %s[%d] = {\n%s\n};\n" % (ctype, name, len(vals), "\n".join(lines))


fb = SK.mel_filterbank(FS, layout=LAYOUT)
lo_n, flat = [], []
for b in range(SK.MEL_BANDS):
    idx = np.nonzero(fb[b])[0]
    if len(idx) == 0:
        lo_n.append((0, 0)); continue
    lo, hi = int(idx[0]), int(idx[-1]) + 1
    lo_n.append((lo, hi - lo))
    flat.extend(fb[b][lo:hi].tolist())

win = np.hanning(SK.NFFT)
out = ["// GENERATED by firmware/gen_mel.py -- do not edit.",
       "// Self-contained: window, filterbank and the sizes that define the wire format, so a node",
       "// sketch does not have to drag in golden.h and its 48000-sample test vector.",
       "#pragma once", "#include <stdint.h>",
       "", "#define MEL16_FS     %.1ff" % FS,
       "#define MEL16_HOP    %d" % max(1, int(SK.HOP_S * FS)),
       "#define MEL16_NFFT   %d" % SK.NFFT,
       "#define MEL16_BANDS  %d" % SK.MEL_BANDS,
       "#define MEL16_FRAMES %d" % SK.FRAMES,
       "#define MEL16_FRAME_BYTES %d" % SK.wire_size(),
       "",
       "// The frame states its own rate and band layout: flags bits 8-11 carry the rate code and",
       "// bit 12 says these edges are on the shared [F_LO, F_HI] axis rather than rescaled to this",
       "// node's Nyquist. Without them a consumer cannot tell a 16 kHz frame from a 48 kHz one and",
       "// band k is a different frequency in each.",
       "#define MEL16_FS_CODE    %d" % SK.fs_code(FS),
       "#define MEL16_LAYOUT_BIT 0x%04x" % (SK.LAYOUT_BIT if LAYOUT == SK.LAYOUT_FIXED else 0),
       "#define MEL16_FLAG_BITS  ((MEL16_FS_CODE << %d) | MEL16_LAYOUT_BIT)" % SK.FS_SHIFT,
       "// Bands with any bin below Nyquist. The rest are empty BY CONSTRUCTION, not quiet.",
       "#define MEL16_VALID_BANDS %d" % SK.valid_bands(FS, layout=LAYOUT), "",
       carr("MEL16_WIN", ["%.9ef" % v for v in win], per=6),
       carr("MEL16_FB_LO", [v[0] for v in lo_n], per=20, ctype="uint16_t"),
       carr("MEL16_FB_N", [v[1] for v in lo_n], per=20, ctype="uint16_t"),
       carr("MEL16_FB_W", flat)]
here = os.path.dirname(os.path.abspath(__file__))
for sub in ("path_test", "night_node"):
    p = os.path.join(here, sub, "mel16.h")
    os.makedirs(os.path.dirname(p), exist_ok=True)
    open(p, "w").write("\n".join(out))
    print("wrote %s" % p)
print("fs %.0f  layout %s  hop %d  %d weights  valid_bands %d/%d"
      % (FS, LAYOUT, max(1, int(SK.HOP_S * FS)), len(flat),
         SK.valid_bands(FS, layout=LAYOUT), SK.MEL_BANDS))
